// <auto-generated />
using System;
using FCQI.Infrastructure.Persistence;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace FCQI.Infrastructure.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20260830235519_InitialCreate")]
    partial class InitialCreate
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.30")
                .HasAnnotation("Relational:MaxIdentifierLength", 64);

            MySqlModelBuilderExtensions.AutoIncrementColumns(modelBuilder);

            modelBuilder.Entity("FCQI.Domain.Entities.Advisor", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("varchar(150)");

                    b.Property<string>("FullName")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("varchar(200)");

                    b.HasKey("Id");

                    b.HasIndex("Email")
                        .IsUnique();

                    b.ToTable("advisors", (string)null);
                });

            modelBuilder.Entity("FCQI.Domain.Entities.AdvisorySession", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("AdvisorId")
                        .HasColumnType("int");

                    b.Property<int?>("AvailabilityId")
                        .HasColumnType("int");

                    b.Property<DateTime>("ScheduledAt")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("varchar(50)");

                    b.Property<int>("StudentId")
                        .HasColumnType("int");

                    b.Property<int>("SubjectId")
                        .HasColumnType("int");

                    b.Property<string>("Topic")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("varchar(500)");

                    b.HasKey("Id");

                    b.HasIndex("AdvisorId");

                    b.HasIndex("AvailabilityId");

                    b.HasIndex("StudentId");

                    b.HasIndex("SubjectId");

                    b.ToTable("advisory_sessions", (string)null);
                });

            modelBuilder.Entity("FCQI.Domain.Entities.Availability", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("AdvisorId")
                        .HasColumnType("int");

                    b.Property<int>("DayOfWeek")
                        .HasColumnType("int");

                    b.Property<TimeOnly>("EndTime")
                        .HasColumnType("time(6)");

                    b.Property<string>("Location")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("varchar(200)");

                    b.Property<int>("MaxCapacity")
                        .HasColumnType("int");

                    b.Property<string>("Modality")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("varchar(50)");

                    b.Property<TimeOnly>("StartTime")
                        .HasColumnType("time(6)");

                    b.HasKey("Id");

                    b.HasIndex("AdvisorId");

                    b.ToTable("availabilities", (string)null);
                });

            modelBuilder.Entity("FCQI.Domain.Entities.Student", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("varchar(150)");

                    b.Property<string>("FullName")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("varchar(200)");

                    b.Property<string>("StudentNumber")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("varchar(20)");

                    b.HasKey("Id");

                    b.HasIndex("Email")
                        .IsUnique();

                    b.HasIndex("StudentNumber")
                        .IsUnique();

                    b.ToTable("students", (string)null);
                });

            modelBuilder.Entity("FCQI.Domain.Entities.Subject", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Code")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("varchar(20)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("varchar(200)");

                    b.Property<string>("Program")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("varchar(100)");

                    b.HasKey("Id");

                    b.HasIndex("Code")
                        .IsUnique();

                    b.ToTable("subjects", (string)null);

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Code = "MAT101",
                            Name = "Matemáticas I",
                            Program = "Tronco Común"
                        },
                        new
                        {
                            Id = 2,
                            Code = "FIS101",
                            Name = "Física I",
                            Program = "Tronco Común"
                        },
                        new
                        {
                            Id = 3,
                            Code = "QUI201",
                            Name = "Química Orgánica",
                            Program = "Química"
                        },
                        new
                        {
                            Id = 4,
                            Code = "ING301",
                            Name = "Termodinámica",
                            Program = "Ingeniería Química"
                        },
                        new
                        {
                            Id = 5,
                            Code = "CAL101",
                            Name = "Cálculo Diferencial",
                            Program = "Tronco Común"
                        });
                });

            modelBuilder.Entity("FCQI.Domain.Entities.AdvisorySession", b =>
                {
                    b.HasOne("FCQI.Domain.Entities.Advisor", "Advisor")
                        .WithMany("AdvisorySessions")
                        .HasForeignKey("AdvisorId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("FCQI.Domain.Entities.Availability", "Availability")
                        .WithMany("AdvisorySessions")
                        .HasForeignKey("AvailabilityId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.HasOne("FCQI.Domain.Entities.Student", "Student")
                        .WithMany("AdvisorySessions")
                        .HasForeignKey("StudentId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("FCQI.Domain.Entities.Subject", "Subject")
                        .WithMany("AdvisorySessions")
                        .HasForeignKey("SubjectId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Advisor");

                    b.Navigation("Availability");

                    b.Navigation("Student");

                    b.Navigation("Subject");
                });

            modelBuilder.Entity("FCQI.Domain.Entities.Availability", b =>
                {
                    b.HasOne("FCQI.Domain.Entities.Advisor", "Advisor")
                        .WithMany("Availabilities")
                        .HasForeignKey("AdvisorId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Advisor");
                });

            modelBuilder.Entity("FCQI.Domain.Entities.Advisor", b =>
                {
                    b.Navigation("AdvisorySessions");

                    b.Navigation("Availabilities");
                });

            modelBuilder.Entity("FCQI.Domain.Entities.Availability", b =>
                {
                    b.Navigation("AdvisorySessions");
                });

            modelBuilder.Entity("FCQI.Domain.Entities.Student", b =>
                {
                    b.Navigation("AdvisorySessions");
                });

            modelBuilder.Entity("FCQI.Domain.Entities.Subject", b =>
                {
                    b.Navigation("AdvisorySessions");
                });
#pragma warning restore 612, 618
        }
    }
}
